import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './NavBar'
import "./globals.css";
import Navbar from "./NavBar";
import AuthProvider from "@/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Navbar /> 
          {children}
        </body>
      </html>
      </AuthProvider>
  );
}
